### ISSUE TITLE
Uploading to the Perl6 ecosystem?

### ISSUE THREAD

**Issue by JJ** [trizen/Data-Dump-Perl6#1]
It would be interesting to have it there.

**Comment by coke** [comment]
Even if it's not in the ecosystem, it would be nice to able to do "zef install ." from inside a checkout.

**Comment by trizen** [comment]
This is a (highly experimental) Perl 5 module, not a Perl 6 one. Also, personally, I don't have any interests in working on it anymore. At some point, it was available in the CPAN, but I decided to delete it because it has some serious limitations (one of which is the lack of dumping regular expressions) and since it's no longer in active development, there was no point to keep it on the CPAN anymore.
